### PR TITLE
feat(prim): add Prim's algorithm for finding MST

### PR DESCRIPTION
**Pull request by jafar75**
This a try to implement Prim's algorithm that is useful to find minimum spanning tree for an undirected graph.
For some cases, specially when the graph is dense, Prim is more efficient than Kruskal

After successful merge of this PR, issue #576 can be closed

### CODE REVIEW

**Comment by jafar75** [comment]
Thanks @samueltardieu for squashing and refactoring. I saw the branch you create and everything is fine IMO.

**Comment by jafar75** [comment]
@samueltardieu Do I need to create another PR by the branch you created, or it can be automatically merged?

**Comment by samueltardieu** [comment]
I'll take care of it, then I'll close this one with a reference to it and release a new version of pathfinding containing your code.

**Comment by samueltardieu** [comment]
Thanks @jafar75, pathfinding 4.11.0 has just been released with your implementation of Prim's algorithm.

**Pull request closed without merging**
