### PR TITLE
Implement Bron-Kerbosch algorithm

### PR DESCRIPTION
**Pull request by gzsombor**
to find maximal cliques in a graph.

### CODE REVIEW

**Comment by samueltardieu** [comment]
This looks nice, thanks! Could you please just amend the commit title to use a [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) message, such as `feat: implement Bron-Kerbosch algorithm`?

**Comment by samueltardieu** [comment]
(and also follow clippy's suggestion to use `.sort_unstable()`)

**Comment by gzsombor** [comment]
Fixed! Thanks for the quick review.

**Comment by samueltardieu** [comment]
I just released [pathfinding 4.13.0](https://github.com/evenfurther/pathfinding/releases/tag/v4.13.0) with your implementation. Thanks.

*Note: that required a force push to allow a release without bumping the MSRV, just in case you have a copy of the repository checked out*

**Pull request merged**
